steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/werk-backend-dev:$COMMIT_SHA', 'api']

 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/werk-backend-dev:$COMMIT_SHA']

 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'werk-backend-dev'
   - '--image'
   - 'gcr.io/$PROJECT_ID/werk-backend-dev:$COMMIT_SHA'
   - '--update-secrets'
   - 'DB_USER=DB_USER_DEV:latest'
   - '--update-secrets'
   - 'DB_NAME=DB_NAME_DEV:latest'
   - '--update-secrets'
   - 'DB_PASSWORD=DB_PASSWORD_DEV:latest'
   - '--update-secrets'
   - 'DB_HOST=DB_HOST_DEV:latest'
   - '--update-secrets'
   - 'DB_PORT=DB_PORT_DEV:latest'
   - '--allow-unauthenticated'
   - '--region'
   - 'europe-north1'

images:
  - 'gcr.io/$PROJECT_ID/werk-backend-dev:$COMMIT_SHA'

