steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/werk-ui-dev:$COMMIT_SHA', 'werk-web']

 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/werk-ui-dev:$COMMIT_SHA']

 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'werk-ui-dev'
   - '--image'
   - 'gcr.io/$PROJECT_ID/werk-ui-dev:$COMMIT_SHA'
   - '--allow-unauthenticated'
   - '--region'
   - 'europe-north1'

images:
  - 'gcr.io/$PROJECT_ID/werk-ui-dev:$COMMIT_SHA'
